### ISSUE TITLE
Missing WireGuard Kernel Module Despite Installing WireGuard On Ubuntu Host

### ISSUE THREAD

**Issue by cjsteward** [hassio-addons/addon-wireguard#10]
I'm still receiving the error message "[!] Missing WireGuard kernel module. Falling back to slow userspace implementation." despite installing WireGuard on the host Ubuntu OS. 

Intel NUC J5005
Ubuntu 18.04.3 LTS
Hassio 0.98.1

Here are the WireGuard Addon logs:

 [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: WireGuard
 Fast, modern, secure VPN tunnel
-----------------------------------------------------------
 Add-on version: 0.1.1
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.98.1
 Supervisor version: 184
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] config.sh: executing... 
[23:06:47] DEBUG: Requested API resource: http://hassio/dns/info
[23:06:47] DEBUG: Request method: GET
[23:06:47] DEBUG: Request data: {}
[23:06:47] DEBUG: API HTTP Response code: 200
[23:06:47] DEBUG: API Response: {"result": "ok", "data": {"version": "1", "latest_version": "1", "host": "172.30.32.3", "servers": ["dns://8.8.8.8", "dns://1.1.1.1"], "locals": []}}

[cont-init.d] config.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:06:49] INFO: Starting WireGuard...
[#] ip link add wg0 type wireguard
RTNETLINK answers: Not supported
[#] wireguard-go wg0
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
WARNING WARNING WARNING WARNING WARNING WARNING WARNING
W                                                     G
W   You are running this software on a Linux kernel,  G
W   which is probably unnecessary and foolish. This   G
W   is because the Linux kernel has built-in first    G
W   class support for WireGuard, and this support is  G
W   much more refined than this slower userspace      G
W   implementation. For more information on           G
W   installing the kernel module, please visit:       G
W           https://www.wireguard.com/install         G
W                                                     G
WARNING WARNING WARNING WARNING WARNING WARNING WARNING
INFO: (wg0) 2019/09/01 23:06:49 Starting wireguard-go version v0.0.20190805
[#] wg setconf wg0 /dev/fd/63
INFO: (wg0) 2019/09/01 23:06:49 Starting wireguard-go version v0.0.20190805
INFO: (wg0) 2019/09/01 23:06:49 Device started
INFO: (wg0) 2019/09/01 23:06:49 UAPI listener started
[#] ip -4 address add 172.27.66.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
INFO: (wg0) 2019/09/01 23:06:49 Interface set up
[#] resolvconf -a wg0 -m 0 -x
ERROR: (wg0) 2019/09/01 23:06:49 peer(xqo5…s5nE) - Failed to send handshake initiation no known endpoint for peer
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
ERROR: (wg0) 2019/09/01 23:06:54 peer(xqo5…s5nE) - Failed to send handshake initiation no known endpoint for peer

Thank you in advance for any help. Thank you too for everything you have done for the HomeAssistant community!!

**Comment by cjsteward** [comment]
After doing a litle more research, it seems like this issue can be caused by having Secure Boot enabled. I'll provide an update when I get a chance to get into the UEFI

**Comment by cjsteward** [comment]
Sorry for the delay. I was just able to confirm that disabling Secure Boot in the UEFI resolves this issue. 

Thanks again for another great addon!

**Comment by frenck** [comment]
Thanks for letting me know! Nice! 👍

**Comment by silfa718** [comment]
Is disabling Secure Boot, the best fix for this issue?
