### ISSUE TITLE
error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system

### ISSUE THREAD

**Issue by gomerust** [hassio-addons/addon-wireguard#107]
# Problem/Motivation

wireguard doesn't work with
 Add-on version: 0.5.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.4.4
 Home Assistant Supervisor: 2021.04.0

## Expected behavior

should be able to write into /sys ? And be able to start the service 

## Actual behavior

Service tries to start cant write into sys and stops the service again
the log shows
```
-----------------------------------------------------------
 Add-on: WireGuard
 Fast, modern, secure VPN tunnel
-----------------------------------------------------------
 Add-on version: 0.5.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.4.4
 Home Assistant Supervisor: 2021.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] config.sh: executing... 
[cont-init.d] config.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:15:58] INFO: Starting WireGuard...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.27.66.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0

```
## Steps to reproduce

restart the service with wireguard version 0.5.1 

## Proposed changes

as the [Docker Forum](https://forums.docker.com/t/sysctl-error-setting-key-net-ipv4-conf-all-src-valid-mark-read-only-file-system/92567/4) suggests the usage of --privileged to get it working i would propose doing the same here.

Thanks ;-)

**Comment by frenck** [comment]
`--privileged` is not an option for add-on and generally not a solution for anything. It simply set a "superuser" flag, which is 99% of the cases overused and really unnecessary force that no one should ever use.

That said, there is currently no way for an add-on to write to that point. It's not a problem either, as it would be only needed for a client mode use of the add-on, which is not supported anyway.

**Comment by gomerust** [comment]
but how should the addon run then? since i don't get it to work this way.
