### ISSUE TITLE
Add on does not start

### ISSUE THREAD

**Issue by nicolasbisi** [hassio-addons/addon-wireguard#11]
# Problem/Motivation
The add on start and stop pretty much immediately

## Expected behavior
To run.

## Steps to reproduce
Running 0.98.1 on a VM running on a MacMini (10.14.3)

Config
```
{
  "server": {
    "host": "*myhost",
    "addresses": [
      "192.168.0.1"
    ],
    "dns": [
      "192.168.0.250"
    ]
  },
  "peers": [
    {
      "name": "*myDeviceName",
      "addresses": [
        "192.168.0.249"
      ],
      "allowed_ips": [],
      "client_allowed_ips": []
    }
  ],
  "log_level": "trace"
}
```

*changed to post here

My log is empty.

**Comment by TychoWerner** [comment]
Not sure but, in the video Frenck released he said it couldn't be in the same IP range as your own.
Maybe that is this?

**Comment by nicolasbisi** [comment]
> Not sure but, in the video Frenck released he said it couldn't be in the same IP range as your own.
> Maybe that is this?
Thanks for the suggestion. I tried to change that but got the same behaviour.

**Comment by frenck** [comment]
Please provide the Hass.io system logs at the moment the startup fails.

**Comment by nicolasbisi** [comment]
> Please provide the Hass.io system logs at the moment the startup fails.

Hi @frenck thanks for this and all the other add-on

Here's what I'm gettin

`19-09-02 09:22:42 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_a0d7b954_wireguard application
19-09-02 09:22:42 ERROR (SyncWorker_2) [hassio.docker] Can't start addon_a0d7b954_wireguard: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/net/tun": no such file or directory")`

**Comment by frenck** [comment]
Please provide information on your running system, e.g. by running `hassio info` in one of the SSH add-ons.

**Comment by nicolasbisi** [comment]
Here it is
```
info
arch: amd64
channel: stable
hassos: "1.13"
homeassistant: 0.98.1
hostname: hassio
logging: info
machine: qemux86-64
supervisor: "184"
supported_arch:
- amd64
- i386
timezone: Pacific/Auckland
```

**Comment by frenck** [comment]
You HassOS is outdated (like majorly outdated). Please upgrade it to the current latest stable: 2.12.

**Comment by nicolasbisi** [comment]
@frenck Spot on. Its all working fine now. Havent realised that I need to update the OS as well. I thought it was part of Hassio.
Thanks a lot
