### ISSUE TITLE
Please Upgrade addon to wireguard go 0.0.20210424

### ISSUE THREAD

**Issue by Delta1977** [hassio-addons/addon-wireguard#116]
Please Upgrade addon to wireguard go 0.0.20210424 

 go ≥ 1.16. required

**Comment by frenck** [comment]
No.

**Comment by Delta1977** [comment]
ok, so i will contribute as i can.
Problem is that go ≥ 1.16. is required, but is only available in Apline edge.
So i will wait to next Alpine release.

Thank you for quick response
