### ISSUE TITLE
add-on does not start

### ISSUE THREAD

**Issue by Stephan296** [hassio-addons/addon-wireguard#12]
The wire-guard add-on does not start, the hassio log shows:

`19-09-04 03:54:11 ERROR (SyncWorker_2) [hassio.docker] Can't start addon_a0d7b954_wireguard: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/net/tun": no such file or directory")`

HASSIO info:

arch: amd64
channel: stable
hassos: "2.11"
homeassistant: 0.98.2
hostname: hassio
logging: info
machine: intel-nuc
supervisor: "185"
supported_arch:
- amd64
- i386
timezone: Europe/Amsterdam

**Comment by tjorim** [comment]
Update HassOS to 2.12.

**Comment by Stephan296** [comment]
Thx, I didn't know that I could update hassos in hassio. I have update it now :-)
