### ISSUE TITLE
Incorrect configuration without private_key file

### ISSUE THREAD

**Issue by wolfbl** [hassio-addons/addon-wireguard#120]
# Problem/Motivation

If peers.private_key is specified in the add-on configuration, no private_key file is created under ssl / wireguard / ClientXX. If this file is not created, an invalid client.conf is then created.

In order to generate a valid client.conf, it is sufficient to put an empty text file with the name "private_key" in the respective folder. Even if this file is actually not needed. 

## Expected behavior

It must be possible to create a valid client.conf by specifying peers.private_key without a private_key file in the respective folder. 

## Actual behavior

Look at Steps to reproduce

## Steps to reproduce

1. Create a new Client in Addon-Config with private_key
2. Restart the Addon to generate new Config
3. The client.conf is invalid, becouse there is no private_key in the file

## Proposed changes

Look in Problem/Motivation

**Comment by frenck** [comment]
I'm not storing a custom-provided private key. There is not need to either.
