### ISSUE TITLE
Add-on config 'snapshot_exclude' is deprecated

### ISSUE THREAD

**Issue by theetron** [hassio-addons/addon-wireguard#165]
# Problem/Motivation

In supervisor log I see a warning:
`WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home.`

## Expected behavior

No warnings in the supervisor log

## Actual behavior

During startup of HA, I see a waring in the supervisor log.

## Steps to reproduce
Versions:
Hardwar: PI3
core-2021.10.6
supervisor-2021.10.8
Wireguared: 0.5.1 

Install the addon Wireguard en restart HA and look at the supervisor logs.

**Comment by frenck** [comment]
This is not adguard...

**Comment by theetron** [comment]
How can I be so blind? Sorry Frenck
