### ISSUE TITLE
Wireguard Won't Start

### ISSUE THREAD

**Issue by MagicMountainMan** [hassio-addons/addon-wireguard#17]
I'm getting the same error that others have already reported, however I'm running HASSOS 3.0 so my solution is not an out of date OS.

Error:
`Can't start addon_a0d7b954_wireguard: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/net/tun": no such file or directory")`

Info:
arch: amd64
channel: stable
hassos: "3.0"
homeassistant: 0.99.2
hostname: hassio
logging: info
machine: qemux86-64
supervisor: "188"
supported_arch:
- amd64
- i386
timezone: America/Los_Angeles

Running Hass.io as a VM in Unraid. I've been doing this for a while so not sure if the VM is still best practice or not...

**Comment by sinclairpaul** [comment]
This is very likely an Unraid issue, you would need to look as to why the OS isn't passing /dev/net/tun to HassOS.

**Comment by sinclairpaul** [comment]
Just to add from looking around it appears that Unraid support for Wireguard in the kernel is not yet available so you probably want to wait for that.

https://forums.unraid.net/topic/76162-wireguard-vpn-support/

**Comment by frenck** [comment]
HassOS 3.0 is actually outdated...
