### ISSUE TITLE
[Help] : Connect ubuntu server 18.04 (client) to addon-wireguard (server)

### ISSUE THREAD

**Issue by vipk31** [hassio-addons/addon-wireguard#18]
I installed and connected from phone to addon-wireguard successfully
But I don't know how to connect from ubuntu server 18.04 to addon-wireguard
Please guide step by step help me

**Comment by frenck** [comment]
We use GitHub to track issue, for support please join our Discord server or go the Home Assistant forums (WireGuard add-on topic). Thanks 👍
