### ISSUE TITLE
Wrong logging behaviour

### ISSUE THREAD

**Issue by rickycraft** [hassio-addons/addon-wireguard#188]
# Problem/Motivation

The addon logs the wireguard configuration even if the log level is set above info.

## Expected behavior

The configuration does not get logged

## Actual behavior

The configuration gets logged

## Steps to reproduce

Set the log level to warning and show the log tab

## Proposed changes

Making the logging of the configuration follow the logging configuration.

**Comment by rickycraft** [comment]
Any news?

**Comment by mcsrobert** [comment]
Same issue here. I've set the log level to warning to reduce the writes to my SD card but I keep getting the wireguard config spammed in the logs.

**Comment by bens545** [comment]
Looks like a fix was proposed in #183, however it went stale and was closed.

**Comment by rickycraft** [comment]
Should be an easy fix. I hope some mantainers  (@frenck) see this issue and have the time to fix this.

**Comment by bens545** [comment]
I'd look at fixing it if I knew the reason the previous fix wasn't accepted.

**Comment by frenck** [comment]
This is not wrong; but working as intended.

The log setting controls add-on logs, not Wireguard logging.

**Comment by andriej** [comment]
Is there any way to fix wireguard logging?

I've just experience death of my previous disk (SSD).
I'd love to keep 'informational' spam as low as possible... Wireguard logs a lot :(

**Comment by frenck** [comment]
If this little bit of logging kills your SSD, you might want to look into buying a decent SSD 😟 

The logging is quite low compared to other parts of the Home Assistant system. As for asking for a "Fix"; its not a bug but by design.

**Comment by rickycraft** [comment]
I can see both side of the argument. I personally have killed an sdcard of my raspberry using home assistant.

Is it possible to maybe add a flag to log or not the wireguard output? It should be quite easy and i am all for customization. The default is on but for people like me and @andriej that are worried of excessive logging we can disable it.
