### ISSUE TITLE
Configuration simplification/suggestion

### ISSUE THREAD

**Issue by keatontaylor** [hassio-addons/addon-wireguard#2]
# Problem/Motivation

I understand that the goal of this addon is to provide a solid and simplified experience for using this add-on as a server for clients to connect to. Having used the component for a while I see that it will automatically generate the client config and provide a QR code for users to get the config to their clients. 

However, I do think the idea of the server generated private keys for the client to use is a not ideal for ensuring the highest level of security for this tunneling protocol. 

Ideally, clients should generate their private and public key themselves and provide the public key to the wireguard server (this add-on). This ensures that the private key never leaves the client that it is intended for. The wireguard mobile, mac and windows app all have easy ways to create a new tunnel config that will automatically generate public and private keys that can be shared from the clients. 

I understand this isn't as fool proof, but I'd argue that those who are familiar with wireguard understand that private keys should never leave their intended system and should never be shared to ensure the highest level of security. 

## Expected behavior

Remove generating private keys for peers, instead require the user to specify the public keys for each connecting peer and encourage generating the private/public keypair on the client that will ultimately use them.

## Actual behavior

Startup will currently generate private keys for the peers if none are provided. Private keys for peers should not be shared with the server for the highest level of security.

## Steps to reproduce

N/A

## Proposed changes

As defined in expected behavior.

**Comment by frenck** [comment]
If you actually have read code or documentation, you would have discovered that you can actually do that.

Please note, this addon is not released yet and in active development.

**Comment by frenck** [comment]
I've adjusted the documentation to make this more clear.

- Added multiple notes on the best practice to provide public keys.
- Added `recommended` to `peer.public_key` heading.
- Adjusted initial example to include a peer with a public key set.
