### ISSUE TITLE
Bad IP forwarding instructions

### ISSUE THREAD

**Issue by remdot** [hassio-addons/addon-wireguard#21]
# Problem/Motivation

The listed IP forwarding commands in README.md will not work with sudo (and if it did it would wipe out anything in /etc/sysctl.conf)

## Proposed changes

sudo echo "net.ipv4.ip_forward = 1" > /etc/sysctl.conf 

should be:

echo "net.ipv4.ip_forward = 1" | sudo tee -a  /etc/sysctl.conf

**Comment by frenck** [comment]
Has been fixed in the current master version.
