### ISSUE TITLE
Wireguard client?

### ISSUE THREAD

**Issue by fremut** [hassio-addons/addon-wireguard#22]
Is it possible use this add-on as wireguard client ? Thanks

**Comment by frenck** [comment]
It won't be much use, since it runs in an isolated Docker network.

**Comment by fremut** [comment]
For example id want to connect to Hassio from the internet without public IP ?

**Comment by palhaland** [comment]
It is possible, although you would have to know (and forward) the physical IP address/subnet it has on it's local network to get access to it.

I have configured it like a client where it connects to a wireguard server, and I can access it either through a nginx instance or trough the another wireguard client. The only thing I'm missing is the possibility to access the hassio from the wireguard IP and not necessarily the physical ip of the hassos . (As frenck commented it is in an isolated Docker network)

I don't have the configuration I use at hand at the moment, but can post it later.
