### ISSUE TITLE
How to remove peer/user?

### ISSUE THREAD

**Issue by sotoje** [hassio-addons/addon-wireguard#23]
# Problem/Motivation
I would like ti know how to remove user, deleting the files in ssl folder user is able to connect 
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
Create user, delete files an the user continue active
> (How can someone else make/see it happen)

## Proposed changes
If the user is remove in config file the connexion will be disabled
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Remove it from the add-on configuration and restart the add-on.

**Comment by sotoje** [comment]
It does not work, i deleted it from config and also the files from filesystem, and the user is able to connect

**Comment by frenck** [comment]
Ok, I will try to reproduce.

**Comment by frenck** [comment]
I cannot reproduce it. Removing the user from the add-on configuration removes the user.

The add-on does not keep/store the configuration, it is generated on the fly each restart. Hence, there is never a residue from previous runs.
