### ISSUE TITLE
Optional list-based config parameters are required for save

### ISSUE THREAD

**Issue by zandervalle** [hassio-addons/addon-wireguard#239]
# Problem/Motivation

When creating a configuration for the wireguard addon, i removed the server.dns ([which should be optional](https://github.com/hassio-addons/addon-wireguard/blob/main/wireguard/DOCS.md#option-serverdns-optional)) section since i dont do dns on my wireguard network. While trying to save the config i'll get:

```
Failed to save add-on configuration, Missing option 'dns' in server in WireGuard (a0d7b954_wireguard).  Got 
{
  'server': 
  {
    'host': '<my_ha_host>', 
    'addresses': ['<my_ha_wg_addr>'], 
    'private_key': '<>', 
    'public_key': '<public_key>, 
    'post_up': 'off', 
    'post_down': 'off'
  }, 
  'peers': 
  [
    {
      'name': '<peer1_name>',
      'public_key': '<peer1_public_key>',
      'endpoint': '<peer1_public_ip>',
      'addresses': ['<peer1_wg_address>'],
      'client_allowed_ips': ['<peer1_wg_address>/32']
    }
  ]
}
```

Whe re-adding the dummy `dns: []` i got the same kind of error, but for `peer.allowed_ips` and `peer.client_allowed_ips`. I dont need those parameters as the docu says it defaults to the address of the peer and the catch-all `0.0.0.0/0` repectively

## Expected behavior

I would expect that an optional parameter as metioned in the `DOCS.md` is negligible in the config file to the addon

## Actual behavior

Currentlx it it not clear which parameters are needed in order to have a 'valid' an 'saveable' configuration.

## Steps to reproduce

1. Add the wireguard addon to homeassistant
2. Open up the addon configuration and remove the line `dns: []` from the example server configuration.
3. Try to save

## Proposed changes

The current workaround is to add dummy lists, or fill the allowed_ips manually with the addresses of an peer.

It seems that there have to be changes made in [config.yaml](https://github.com/hassio-addons/addon-wireguard/blob/main/wireguard/config.yaml)

**Comment by sinclairpaul** [comment]
I think it's the understanding of "optional" the config item needs to be there, but can be blank in which case it will use the system DNS https://github.com/hassio-addons/addon-wireguard/blob/25a6a07aa134d9f3e4bd8538a3c337709fb2d7ce/wireguard/rootfs/etc/cont-init.d/config.sh#L58

**Comment by sinclairpaul** [comment]
You can always look at the source to see the config values needed https://github.com/hassio-addons/addon-wireguard/blob/c5787915ea57b4425390eee34464d21dc053bfed/wireguard/config.yaml#L40

**Comment by frenck** [comment]
Thanks for the issue, Emory is fine and would be handled as not set.

Home Assistant currently offers no way to make list configuration item keys optional in an add-on.

This is thus nothing the add-on can solve. Closing the issue for that reason.


../Frenck
