### ISSUE TITLE
Use as a client to an existing server

### ISSUE THREAD

**Issue by robin13** [hassio-addons/addon-wireguard#24]
# Problem/Motivation

Documentation for using as a client

## Expected behavior

Ability to configure this wireguard as a client connecting to an external server

## Actual behavior

It may be that it is possible, but I have not been able to find documentation...

## Proposed changes

Documentation examples of how to use this wireguard as a peer connecting to a server (currently it is only documented how to use it as a server to which other peers would connect).

**Comment by frenck** [comment]
Your question is not clear. There is no client/server in WireGuard.

**Comment by thedesp** [comment]
I think what OP request is an alternative mode to user this addon to connect to another wireguard endpoint, hassio is the connecting "peer" in this situation.

**Comment by frenck** [comment]
That is possible, however, it is hard.
The add-on was in general not designed for that. To achieve that, you'll need to have quite some decent knowledge of Linux, Docker and routing in general. The add-on runs on an isolated network and routes traffic out of the add-on. Routing traffic back in, is a whole different cup of coffee. 

Honestly, if you are looking for that kinda functionality, I would actually not recommend doing that with the add-on.
