### ISSUE TITLE
IPv6 Issues

### ISSUE THREAD

**Issue by pman07** [hassio-addons/addon-wireguard#25]
# Problem/Motivation

It seems like T-Mobile doesn't like IPv4 VPN, I'm trying to get IPv6 running. 

## Actual behavior

On startup, I get an error "RTNETLINK answers: Permission denied". What am I missing?

## Steps to reproduce

My Config:
```
{
  "server": {
    "host": "xxx.duckdns.org",
    "addresses": [
      "172.27.66.1",
      "fd42:42:42::1/64"
    ],
    "dns": [
      "172.30.32.1"
    ]
  },
  "peers": [
    {
      "name": "phone",
      "addresses": [
        "172.27.66.2",
        "fd42:42:42::1/64"
      ],
      "allowed_ips": [],
      "client_allowed_ips": []
    },
    {
      "name": "laptop",
      "addresses": [
        "172.27.66.3"
      ],
      "allowed_ips": [],
      "client_allowed_ips": []
    }
  ]
}
```

My Log:
'''
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: WireGuard
 Fast, modern, secure VPN tunnel
-----------------------------------------------------------
 Add-on version: 0.1.1
 You are running the latest version of this add-on.
 System: HassOS 3.5  (armv7 / raspberrypi4)
 Home Assistant version: 0.102.3
 Supervisor version: 192
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] config.sh: executing... 
[cont-init.d] config.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[01:05:01] INFO: Starting WireGuard...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.27.66.1/24 dev wg0
[#] ip -6 address add fd42:42:42::1/64 dev wg0
RTNETLINK answers: Permission denied
[#] ip link delete dev wg0
```

**Comment by frenck** [comment]
Hass.io does not have IPv6 support.
