### ISSUE TITLE
Does HA listen on Wireguard address ?

### ISSUE THREAD

**Issue by FlorentCoppint** [hassio-addons/addon-wireguard#254]
# Problem/Motivation

I'm using addon-wireguard to do a remote access setup (Nginx frontend proxying to Wireguard).
It seems that nothing listens of 8123 port of Wireguard address after connection is established.
Is it normal ?

## Expected behavior

Expected HA to listen on every address, local one and Wireguard one.

## Actual behavior

Seems HA only listens on local address, not Wireguard's.

**Comment by frenck** [comment]
That coreect, consult the Home Assistant documentation for more information on their HTTP server.

../Frenck
