### ISSUE TITLE
Port Setting is Ignored

### ISSUE THREAD

**Issue by g00gleit** [hassio-addons/addon-wireguard#265]
# Problem/Motivation
Setting a port under the configuration seems to be ignored and the default port of 51820 is used instead. 
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior
Wireguard starts on port 51820   :(
> (What actually happened)

## Steps to reproduce
Set a non default port, and restart the add on and the port will start up on 51820 instead of the specified port.
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Maybe you could provide some details, if it's based on logs it would be expected.

**Comment by g00gleit** [comment]
I'm glad you told me about the log showing the wrong port. New cell provider for my wireguard client uses CGNat and IPV6 so that seems to be the problem :(

I'm closing this issue since there is really no issue.
