### ISSUE TITLE
Cannot connect via Windows addon to WireGuard addon

### ISSUE THREAD

**Issue by CodeFinder2** [hassio-addons/addon-wireguard#27]
# Problem/Motivation
I would like to use the (latest) [Windows client (v.0.0.36](https://download.wireguard.com/windows-client/wireguard-amd64-0.0.36.msi) to connect to my HassIO WireGuard addon (latest v.0.1.1) but whenever I click "Activate" in the GUI, it changes to "Activating..." and then "Deactive" (=> "Status: Active") but I cannot reach any site (neither a site on the Internet nor my local HassIO instance). Note that Linux (Ubuntu 16.04 LTS) and Android (9.0) are working fine so the setup should work.

Here's the log from the Windows client: https://pastebin.com/FViPgae8
(Note that I am also using the Pi-hole addon but that is working fine.)

## Expected behavior
Successfully connect to the WireGuard VPN from Windows (10, 64bit).

## Actual behavior
No site is reachable, HassIO and router in particular.

## Steps to reproduce
- Install Hassio.
- Install and setup WireGuard.
- Install Windows client v.0.0.36 (Windows 10).
- Connect using a generated peer profile from the Hassio addon.

## Proposed changes
No idea how to make it work. I doubt that it relates to the fact that the Windows client is still a beta (since they would most probably not release a software that is even not capable of doing the basics, i.e., establishing a connection).

**Comment by frenck** [comment]
This add-on makes no differences between the used clients. As you've reported yourself already, it works with other clients.

Please file an issue with the Windows client. I can't fix that client from the add-on.
