### ISSUE TITLE
Unknown options are not reported as warnings

### ISSUE THREAD

**Issue by jkufner** [hassio-addons/addon-wireguard#275]
# Problem/Motivation

I've used `preshared_key` instead of `pre_shared_key` and it took several days to find the problem.

## Expected behavior

The logs should contain a warning that `preshared_key` option is unknown. It should not be an error to ensure forward compatibility.

## Actual behavior

The invalid option is quietly ignored.

## Steps to reproduce

Make a typo in the name of an optional option in the configuration.

## Proposed changes

Show a warning and keep going.

**Comment by sinclairpaul** [comment]
Config validation is performed by the supervisor, I doubt there is much we can do here.
