### ISSUE TITLE
Dont generate QRCODE

### ISSUE THREAD

**Issue by Frazou1** [hassio-addons/addon-wireguard#277]
# Problem/Motivation

> I just install wireguard add on and try to find the qrcode but cant find it. I search into all HA and nothing

## Expected behavior

> Get QRCODE or how to configure wireguard client

## Actual behavior

> QRCODE not generated

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Closing this, as it is a request.

The SSL folder is documented and can be accessed using e.g., the samba add-on.

../Frenck
