### ISSUE TITLE
table option on hassio not work

### ISSUE THREAD

**Issue by tronghung8303** [hassio-addons/addon-wireguard#28]
# Problem/Motivation
![image](https://user-images.githubusercontent.com/56241525/71055235-737b8d80-2187-11ea-9eff-136677257068.png)

i had a issue when i edited the config file on hassio. Because i want to edit the routing when i connect vpn.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by tronghung8303** [comment]
I have a log when i add table option on config file
not a valid value for dictionary value @ data['options']. Got {'server': {'host': 'iohome.duckdns.org', 'addresses': ['192.168.200.1'], 'dns': [], 'table': []}, 'peers': [{'name': 'hassio', 'addresses': ['192.168.200.2'], 'allowed_ips': [], 'client_allowed_ips': ['192.168.100.0/24', '192.168.200.0/24']}], 'log_level': 'info'}

**Comment by frenck** [comment]
Table is not a list, but a string.

**Comment by tronghung8303** [comment]
Dear frenck,

Can you help me a example config for table option.

thanks
