### ISSUE TITLE
Not change listening port and can't connect

### ISSUE THREAD

**Issue by Brax84** [hassio-addons/addon-wireguard#293]
# Problem/Motivation

> Change port to another stuck on 51820 in log

## Expected behavior

>When I change the port in the configuration, for example port 51820 to port 51283, this changes in the client configuration file, but does not change the server listening port.

## Actual behavior

> The server port does not change. In the log I see port 51820 listening and I can't connect via the Wireguard iOS client app

## Steps to reproduce

> I stop the add-on, go to configuration, for example change the port to 51823 or another but it always shows 51820/udp.
In the log section it shows "listening port: 51820" and not 51823. I also tried changing the port with the add-on started and not turned off.
I tried removing the add-on , restart HA etc. If I leave port 51820 I can access from the ios app

## System

HomeAssistant on Rpi 3b+
Core : 2024.1.6
Supervisor : 2023.12.1
Operating System: 11.4
Frontend: 20240104.0
 

<img width="1135" alt="Screenshot 2024-02-02 alle 15 39 19" src="https://github.com/hassio-addons/addon-wireguard/assets/22413640/bb91d283-d5a9-46f0-b428-2526aba87d75">
<img width="952" alt="Screenshot 2024-02-02 alle 15 42 37" src="https://github.com/hassio-addons/addon-wireguard/assets/22413640/df13ba23-bb41-4f0f-ac87-5779008f4de4">

**Comment by Brax84** [comment]
I investigated further and it seems to be an "aesthetic problem" with the door change. I changed the ddns domain and now it works

<img width="561" alt="Screenshot 2024-02-02 alle 16 19 05" src="https://github.com/hassio-addons/addon-wireguard/assets/22413640/93648b15-f88b-4ea9-9427-4b772c2ed270">

**Comment by 51av0sh** [comment]
I believe that's by design so you can see the default port regardless of what you change it to (on the left input)
