### ISSUE TITLE
Home Assistant integration 

### ISSUE THREAD

**Issue by txitxo0** [hassio-addons/addon-wireguard#297]
I was on my way to create an automation based on who is connected through the VPN, but then I realized there is no such an integration between wireguard and home assistant, so I can not read any event or log.

Do you think is it suitable to develop something to integration some main events and, maybe, switches (for example to temporary disable a peer)  as a wireguard integration?

**Comment by frenck** [comment]
Everything is possible. However, this is an add-on, not an integration. Different scopes and thus unrelated.

../Frenck
