### ISSUE TITLE
DNS server is the default when kept blanc

### ISSUE THREAD

**Issue by jjtoard** [hassio-addons/addon-wireguard#31]
The DNS server is the default in the range 172.x.x.x while I expected it to forward it to the vpn gateway.
So when left blanc in the config the default should be the VPN gateway.

**Comment by frenck** [comment]
I'm unsure what you mean by the VPN gateway?
Is there such a thing?

**Comment by jjtoard** [comment]
What I exect is that it would take the IP of hassio or the wireguard VPN server.  Hassio knows the DNS.
If I leave it blanc I don't expect it to take a 172.x.x.x adress what was the default of wireguard's IP range.

**Comment by frenck** [comment]
Feel free to override it, by default it should pick up the DNS provided by the Hass.io ecosystem, which it currently does. The DNS location is provided by the Hass.io Supervisor, which is the preferred DNS inside the Hass.io ecosystem.

**Comment by jjtoard** [comment]
In my environment not one of my dns servers is in the 172. range so that is my point. Wireguard doesn't take the dns settings from hassio.

**Comment by frenck** [comment]
Every Hass.io ecosystem runs a DNS server in the 172 range.

The code is right here: <https://github.com/hassio-addons/addon-wireguard/blob/master/wireguard/rootfs/etc/cont-init.d/config.sh#L64>

That asks the Hass.io API for his DNS server in case it is left blanc. This gives the IP address the Hass.io's internal DNS server.
Hass.io's internal DNS server can be configured using the `hassio` command line. Run `hassio dns info` for more information.
