### ISSUE TITLE
[Rest API] The rest API stops to work after HA restart

### ISSUE THREAD

**Issue by Valcob** [hassio-addons/addon-wireguard#34]
# Problem/Motivation

Each time I restart the HA the rest api sensor for wireguard becomes unavailable and the logs state
Error fetching data: http://a0d7b954-wireguard failed with HTTPConnectionPool(host='a0d7b954-wireguard', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e1b94c990>: Failed to establish a new connection: [Errno 111] Connection refused'))

## Expected behavior

Should work as before with no problem

## Actual behavior

Connection is refused
And the rest api is back if the wireguard is restarted

## Steps to reproduce

Restart the HA check the logs and UI for messages. Also if the API port is set for host then try to get the http://HAip:APIport 
Or if you have VScode addon installed then you can try  curl too 
![image](https://user-images.githubusercontent.com/37367415/73296458-7059cf80-4212-11ea-8868-f44f39b64b36.png)

A bit of log here maybe it can help:
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 405, in _async_write_ha_state
>     self.entity_id, state, attr, self.force_update, self._context
>   File "/usr/src/homeassistant/homeassistant/core.py", line 977, in async_set
>     state = State(entity_id, new_state, attributes, last_changed, None, context)
>   File "/usr/src/homeassistant/homeassistant/core.py", line 721, in __init__
>     f"Invalid state encountered for entity id: {entity_id}. "
> homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.wireguard_sensor. State max length is 255 characters.

**Comment by sinclairpaul** [comment]
Does this occur when restarting HA, or restarting the entire server?

**Comment by Valcob** [comment]
@sinclairpaul hey, yeah, sorry for a late replay. I did restart the server too but I can't remember what was the final status there, but for HA restarts it happens all the time. If it's needed I can restart my server too an check the status.

**Comment by sinclairpaul** [comment]
I was actually hoping you would say it only occurred on server restart, and not just an HA reload.  There isn't anything that I am aware of that correlates the addon changing based on just HA restarting.  Only thing I could suggest is altering the timeout for the REST sensor to see if it makes a difference.
