### ISSUE TITLE
Route only 192.168.0.x traffic through wireguard

### ISSUE THREAD

**Issue by SamPhoenix91** [hassio-addons/addon-wireguard#38]
# Problem/Motivation

I'm away 70% of the time (at uni). 
My uni router has an ip range of 192.168.2.x
My home router has an ip range of 192.168.0.x

If I need to change my home router settings I want to be able to type 192.168.0.x to connect. 
I do not want any other traffic being routed through wireguard. (both iPhone and desktop)

## Expected behavior

Typing 192.168.0.x routes to home devices via wireguard
Typing 192.168.2.x connects to uni devices locally
Any other internet traffic is connected to default DNS (Cloudflare)

## Actual behavior

All traffic seems to be routed, typing 192.168.2.x results in "Your Internet access is blocked. Firewall or antivirus software may have blocked the connection."

On iPhone, Snapchats fail to send (Immediately noticed the issue and havent used anything else with the VPN on so likely other issues)

## Steps to reproduce

 N/A

## Proposed changes

N/A

**Comment by frenck** [comment]
This is configurable using the `allowed_ips` and `client_allows_ip`. Please refer to the documentation of the add-on and WireGuard for more information on routing.

**Comment by SamPhoenix91** [comment]
I tried that but got an error. I do not know enough about networks, DNS and such to do it without help

**Comment by frenck** [comment]
The GitHub issue tracker is for tracking bugs and issues. If you need support, please use the Community Forum or the Discord chat server.

Thanks 👍
