### ISSUE TITLE
how to configure as client of a remote wireguard server ?

### ISSUE THREAD

**Issue by davibe** [hassio-addons/addon-wireguard#40]
Can you explain how to configure as a client of a remote wireguard server ? I have at hand the wg0 configuration that would work with a plain wireguard client using wg-quick but i can't figure out how to make it work with this addon. Example
```
[Interface]
PrivateKey = redacted
Address = 192.168.44.15/32

[Peer]
# homea_assistant
PublicKey = redacted
AllowedIPs = 192.168.44.0/24
Endpoint = 159.69.85.180:51820
PersistentKeepalive = 10
```

**Comment by sinclairpaul** [comment]
#39 #24 #22 

Probably a few others, in short you can't.

**Comment by davibe** [comment]
I have created an extension "wireguard client" based on the image of this project. 
In the config you can do

```
wg0: |
  your multiline
  wg0.conf configuration
```

And it will connect to the vpn. Additionally it forwards port 80 to homeassistant:8123 so you can access it from anywhere. If this is useful for anyone I could try to publish it.

**Comment by netcookies** [comment]
I have create an addon either.
The [addon](https://github.com/netcookies/hassio-addons/tree/master/WireguardClientTools) handle two issues:
according `option.json` ( remote lan ip ) 
1. add proper route tables rules 
2. add proper `iptables` rules forward and masquerade
