### ISSUE TITLE
Allow client only configuration

### ISSUE THREAD

**Issue by jquelhas** [hassio-addons/addon-wireguard#41]
# Problem/Motivation

> It is very useful to use hass as wireguard client only, so we can connect external servers that could have services like database, but the configuration do not permit that.

## Expected behavior

> We should be able to generate a configuration like that
[Interface]
Address = <local ip address for the interface>
PrivateKey = <PRIVATE KEY FOR THIS WIREGUARD CLIENT>

[Peer]
PublicKey = <PUBLIC KEY OF THE WIREGUARD SERVER>
AllowedIPs = <ALLOWED IPs>
Endpoint = <PUBLIC ADDRESS AND PORT OF THE WIREGUARD SERVER>
PersistentKeepalive = <PERSISTENT KEEP ALIVE SECONDS>

## Actual behavior

> I have a error because the configuration do not permit a peer section without addresses

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This add-on is not designed to be used as client.
