### ISSUE TITLE
Synology Wireguard not start

### ISSUE THREAD

**Issue by gysmo38** [hassio-addons/addon-wireguard#42]
I have two synology with Hassio. On both Wireguard not start.

I found a way to get it work but need manual configuration.

I have installed the Wireguard package from synology and at each start up need go to docker and give the container hight privileges.

If I do not give thoses privileges, I get this:
20-04-17 15:02:49 ERROR (SyncWorker_12) [supervisor.docker] Can't start addon_a0d7b954_wireguard: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/net/tun": no such file or directory")

The problem is after each reboot of hassio or restart of addons I need to give thoses privileges again. Is there a way to set it?

**Comment by frenck** [comment]
Synology is not a support platform for Home Assistant. Instead, use Home Assistant Core (which does not use add-ons).

**Comment by gysmo38** [comment]
Ok thank. I use hassio on synolgy since a long time and this is the only one problem I get :p
