### ISSUE TITLE
Some fields marked as optional are not

### ISSUE THREAD

**Issue by samueltardieu** [hassio-addons/addon-wireguard#43]
# Problem/Motivation

Using version 0.3.1 of the add-on.

Some fields in the WG HA addon configuration are marked as optional but there is an error when saving the configuration if they are absent:
- `server.dns`
- `peers.allowed_ips`
- `peers.client_allowed_ips`

## Expected behavior

Be able to save the configuration without those optional fields.

## Actual behavior

Omitting one or several of those fields prevents saving with a message "Failed to save addon configuration, not a valid value for dictionary value @ data['options'].". Adding them as empty lists allows the configuration to be saved.

## Steps to reproduce

Try to omit those fields.

## Proposed changes

Either update the online documentation to mark those fields as required or (preferred solution) accept that those fields be absent.

**Comment by frenck** [comment]
They are optional to set as in, an empty list makes it go to the default (`[]`).
Omitting of the full list is not supported by the Home Assistant Supervisor at this point.
