### ISSUE TITLE
Hassio report an unknown error while installed

### ISSUE THREAD

**Issue by Mrivilla** [hassio-addons/addon-wireguard#48]
# Problem/Motivation

> I just use the standard installation process and the system reports an unknown error.

## Expected behavior

> To have wireguard installed.

## Actual behavior

> Installation was not successful. Hassio reports the following in the logs:
20-06-26 06:52:40 ERROR (SyncWorker_21) [supervisor.docker.interface] Can't install hassioaddons/wireguard-amd64:0.3.2 -> 404 Client Error: Not Found ("no such image: hassioaddons/wireguard-amd64:0.3.2: No such image: hassioaddons/wireguard-amd64:0.3.2").

## Steps to reproduce

> Go to Hassio supervisor-->Add-on Store, select Wireguard and click Install

**Comment by frenck** [comment]
404 usually means: out of disk space.
