### ISSUE TITLE
HA not loading

### ISSUE THREAD

**Issue by sunsgs** [hassio-addons/addon-wireguard#50]
Hi there, 
i've installed wireguard on hassio, removed from the router port 8123, configured it with my duckdns address. opened on the router the port 51820 as UDP. Installed wiereguard on both mac and iphone and launched the vpn
> (Why the issue was filed)
This is not working. I tried to remove wifi from my phone, I can access the whole network, in HA as soon i try to access my it says unable to load Home Assistant 

## Expected behavior
It should be correctly log in

## Actual behavior
It is not working

**Comment by sinclairpaul** [comment]
Without logs or config details I doubt anyone can help much...
