### ISSUE TITLE
Add DNS Search domain

### ISSUE THREAD

**Issue by damousys** [hassio-addons/addon-wireguard#56]
I am trying to add a DNS Search domain so I can use server names instead of servername.domain.tld
Is this possible ?
I am running Home Assistant 2020.12.1 on Debian 10

**Comment by frenck** [comment]
There is not really support for that in WireGuard.

Some older documentation article on this, that might work:

https://rakhesh.com/linux-bsd/wireguard-search-domain

**Comment by damousys** [comment]
That's to bad
