### ISSUE TITLE
Supervisor has no internet/DNS connection due to WireGuard addon?

### ISSUE THREAD

**Issue by CodeFinder2** [hassio-addons/addon-wireguard#57]
Hi,

I've already described my problem here in detail: https://community.home-assistant.io/t/supervisor-has-no-internet-dns-connection-due-to-wireguard-addon/257959

TL;DR: My supervisor has no internet connection iff the Wireguard addon is enabled.

Any hints on this? Anything I could try? Please let me know if you need more information!

Thanks!

**Comment by frenck** [comment]
This add-on does not modify the behavior of the host network, as the add-on runs in an isolated network segment. So it is technically incapable of creating the issue you described.

There are some forks around, that do mess with the host network. Are you sure you have the right add-on source repository?

**Comment by CodeFinder2** [comment]
Wow, that was a fast reply, thank you! :-)

Yes, I am just using the official addon repo and zigbee2mqtt:
![image](https://user-images.githubusercontent.com/20599588/102801531-a5848880-43b5-11eb-81f2-9b9617d2284d.png)

If there's something special you want me to try/figure out, please let me know!

**Comment by frenck** [comment]
As said before, the add-on doesn't run on the host network, thus cannot change the host networks working.

**Comment by CodeFinder2** [comment]
Hm okay, do you have a tip for me on how to further debug the issue?

**Comment by frenck** [comment]
I'm sorry, I really don't have an answer for you.

**Comment by CodeFinder2** [comment]
I've just realized that Wireguard show this in its log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: WireGuard
 Fast, modern, secure VPN tunnel
-----------------------------------------------------------
 Add-on version: 0.4.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (armv7 / odroid-xu)
 Home Assistant Core: 2020.12.1
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] config.sh: executing... 
[cont-init.d] config.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:10:37] INFO: Starting WireGuard...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.27.66.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```
@frenck 
1) Isn't it strange that it still starts successfully even if I uninstall all wireguard related packages (`sudo apt purge wireguard*`) on my Debian?
2) According to `ip link show`, there is no interface named `eth0` on my system. Maybe iptables is screwing something up here? Or do I missunderstand the whole thing completely (because you wrote "doesn't run on the host network"). Initially, I just thought to try to update/reinstall the wireguard packages (fwiw...) but realized that `apt` is complaining about unmet deps...

**Comment by frenck** [comment]
> Isn't it strange that it still starts successfully even if I uninstall all wireguard related packages (sudo apt purge wireguard*) on my Debian?

No, it will fall back to a userspace version, which has a lower performance.

> According to ip link show, there is no interface named eth0 on my system. 

As explained above, the add-on runs in an isolated network space. It is NOT your host network that is used there.

**Comment by CodeFinder2** [comment]
Thanks for your quick reply!

> No, it will fall back to a userspace version, which has a lower performance.

 But in a previous version I remember to see some kind of warning that WireGuard is falling back to that userspace version (with lower performance). Has that warning been removed?

> As explained above, the add-on runs in an isolated network space. It is NOT your host network that is used there.

Do have any idea on how I can analyze whether the problem relates to (a) a DNS problem inside the supervisor or (b) not having internet access in the supervisor at all, and/or (c) (and in case of (b)) if its explicitly blocked somehow?

**Comment by frenck** [comment]
> But in a previous version I remember to see some kind of warning that WireGuard is falling back to that userspace version (with lower performance). Has that warning been removed?

No, it hasn't. Kernel module still loaded maybe?

> Do have any idea on how I can analyze whether the problem relates to (a) a DNS problem inside the supervisor or (b) not having internet access in the supervisor at all, and/or (c) (and in case of (b)) if its explicitly blocked somehow?

I'm sorry, I'm going to repeat this one last time.

The add-on doesn't run on the host network, thus cannot change the host networks working. If it does, it is not a problem with the add-on, but a system-level or maybe even a Docker issue.

The add-on should not be able to affect that.

I'm closing this issue as I run down in circles and as explained a number of times now, the add-on cannot affect that.

Nevertheless, Happy Holidays 🎄

**Comment by CodeFinder2** [comment]
> No, it hasn't. Kernel module still loaded maybe?

Impossible, rebooted the host after purging. I understood that the addon "**should** not be able to affect that". However, it's obvious that after activating it, this problem shows up. After disabling it, it's gone.

> Nevertheless, Happy Holidays 🎄

Thanks, u2.

**Comment by CodeFinder2** [comment]
Just a quick update: I **managed to fix it** by using this Armbian image:
https://redirect.armbian.com/region/EU/odroidxu4/Buster_current_minimal  (Buster minimal stable 5.4.y 163M	Dec 12 2020)

instead of this (full re-install):
https://armbian.hosthatch.com/archive/odroidxu4/archive/Armbian_5.98_Odroidxu4_Debian_buster_default_4.14.141_minimal.7z  (Armbian_5.98_Odroidxu4_Debian_buster_default_4.14.141_minimal.7z)

(I explicitly selected the older image/kernel at first to not [lose](https://forum.armbian.com/topic/14198-odroid-xu4-fan-control/?do=findComment&comment=102619) (with kernel 5.x) [fan control support](https://github.com/f1vefour/odroid-xu4-fan-control) on my Odroid XU4.)
