### ISSUE TITLE
Bad default address space

### ISSUE THREAD

**Issue by jamestutton** [hassio-addons/addon-wireguard#6]
# Problem/Motivation

Poor default address space for config.json
...
"addresses": [
        "172.244.66.1"
      ],
...

172.244.66.0/24 is assigned address space as is register to comcast:

https://stat.ripe.net/172.244.66.0#tabId=at-a-glance

## Expected behavior

Use registered private address space from RFC1918 or other blocks:

https://en.wikipedia.org/wiki/Reserved_IP_addresses

## Actual behavior

VPN users would be prevented from accessing services if happen to be on one of the 255 hosts in that range or comcast host a key service on that block.  Although the impact is minor it is poor internet practice and bad manners to reuse assigned addresses.

## Steps to reproduce

NA

## Proposed changes

Use an example form the RFC1918 range as the "default" people dont change things they are lazy.

Suitable options 
10.123.123.1-255
172.16.123.1-255
192.168.123.1-255

Or if want to avoid conflict with local routers then something from 100.64.0.0/10  maybe usable.  

Ulitametly any range you pick risks a glace for someone but at least if the address space used is from the correct ranges then the result will be more predicatable in nature.

**Comment by frenck** [comment]
You are totally right! 🤦‍♂

**Comment by frenck** [comment]
Fixed in v0.1.1, which is being pushed out right now. Thank you so much. I really have no clue on how I missed this, nevertheless, fixed!
