### ISSUE TITLE
Wireguard API availability goes up and down

### ISSUE THREAD

**Issue by czech12** [hassio-addons/addon-wireguard#65]
# Problem/Motivation
Trying to setup HA sensors to monitor Wireguard client connection status using code found here:
https://community.home-assistant.io/t/home-assistant-community-add-on-wireguard/134662/128

I'm experiencing the same issue others have mentioned in that thread, but I haven't seen a resolution.  I also wanted to provide some additional information.

## Expected behavior

API should not lose connectivity.

## Actual behavior

The additional information that I noticed is if I configure a port for the API in the addon configuration (disabled by default), when the API is accessible to my sensors using the http://a0d7b954-wireguard address, it is unavailable from my connection in another browser to my HA server IP using the port I specified (http://192.168.65.55:8080).  As soon as the sensors in HA become unavailable, my browser connection starts working.  It seems to flip back and forth about every 30 seconds, but that time varies as well.

![image](https://user-images.githubusercontent.com/74950455/105799911-97e99200-5f63-11eb-839b-890d877d9e1c.png)

![image](https://user-images.githubusercontent.com/74950455/105800094-fe6eb000-5f63-11eb-9cc8-20ad88895ab7.png)

![image](https://user-images.githubusercontent.com/74950455/105800127-10505300-5f64-11eb-946f-3f5c2576ef59.png)

## Steps to reproduce

Using the API shows the availability bouncing.

## Proposed changes

Hoping that this additional information will help in resolving the issue.

**Comment by czech12** [comment]
This is still an issue for me.  The API continues to bounce up and down.

![image](https://user-images.githubusercontent.com/74950455/109164896-efd50d80-7748-11eb-8a28-bb362ba185b6.png)

**Comment by l3keboy** [comment]
I am also having the issue described above.

**Comment by czech12** [comment]
I'm trying to dig into this issue myself, but I just don't understand enough about docker and how this add-on runs.

I'm doing more testing while SSH'd into HA and I can see that the a0d7b954-wireguard host name and IP address consistently respond to icmp, so the internal network path and name resolution are fine.

However, if I use 'curl a0d7b954-wireguard', when the API is responding to HA and my sensors look good, my curl command fails with connection refused.  Again, just like my original post to open the issue, suddenly the API stops responding to HA and the sensors go down, but then my curl command starts to work.

Something is happening with the API's port 80 binding.  It seems to be flip flopping between interfaces or IP addresses.

I'm hoping somebody who knows more about the code has a eureka moment by seeing this.  Please help.

**Comment by Gorouk** [comment]
Same here.
I experienced it under Home Assistant Operating System and Home Assistant Supervised.

![wg](https://user-images.githubusercontent.com/10878488/114939743-2c67e000-9e41-11eb-84e8-e62d8ea13d4c.PNG)

**Comment by frenck** [comment]
This API is more of a hack than actually useful. I think it should just be removed.

**Comment by JANogueira** [comment]
Please don't remove it.
I also agree with @Gorouk as I use it for my usage statistics.
