### ISSUE TITLE
autogenerated configuration is not valid

### ISSUE THREAD

**Issue by mikalmo1** [hassio-addons/addon-wireguard#7]
# Problem/Motivation

> WireGuard app on iPhone says the autogenerated configuration is not valid

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)
[client.txt](https://github.com/hassio-addons/addon-wireguard/files/3563817/client.txt)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Discussed on Discord, its a config error for the host. Closing.
