### ISSUE TITLE
Example of peer (client) config

### ISSUE THREAD

**Issue by MatejKovacic** [hassio-addons/addon-wireguard#80]
# Problem/Motivation

I would like to connect my Hassio as a peer to existing WireGuard server. Can you please provide me example peer config?

My existing WG peer config (`/etc/wireguard/clients/HomeAssistant.conf`) looks like:
```
[Interface]
PrivateKey = *********************
Address = 10.0.0.3/32
DNS = 1.1.1.1

[Peer]
PublicKey = *********************
AllowedIPs = 0.0.0.0/0
Endpoint = xx.xx.xx.xx:51820
PersistentKeepalive = 25

```

**Comment by frenck** [comment]
The add-on does not support that.

**Comment by MatejKovacic** [comment]
Huh, any plans for support for that?

**Comment by frenck** [comment]
No, I don't have plans to support that.
