### ISSUE TITLE
Status ipv6

### ISSUE THREAD

**Issue by TimoFriedri** [hassio-addons/addon-wireguard#82]
HI,

my intenet provider changed and now I nly have a public ipv6, no real ipv4 anymore.
Wireguard worked fine before with ipv4.
I found #25 that stated there is no ipv6 support in Hass.io.

Now much has changed in the past year. Any update on that.
I personally run HA supervised on Ubuntu. I know, not officially supported, but I think it can be applied 1 to 1 to Debian. 
These OSs  support ipv6 in general.

Should it work, if I try to configure it according to #25 or is it not even worthwhile to try ?

**Comment by frenck** [comment]
IPv6 support has been added to the ecosystem, have not tested it myself though.

**Comment by TimoFriedri** [comment]
Wow, that was quick. Ok, then I will try to set it up this evening. I'll share my experience. Thank you

**Comment by TimoFriedri** [comment]
So far I was not able to add an ipv6 to my wireguard addon

I have the following config:

```
server:
  host: ###.duckdns.org
  addresses:
    - 172.27.66.1
    - 'fd00:0001::1/64'
  dns:
    - 192.168.178.9
    - 'fe80::3f8e:ce0f:8bee:40a8'
```

And I get this in the log

```
[11:14:10] INFO: Starting WireGuard...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.27.66.1/24 dev wg0
[#] ip -6 address add fd00:0001::1/64 dev wg0
RTNETLINK answers: Permission denied
[#] ip link delete dev wg0
```

I am fairly new to ipv6, so maybe I misconfigure something.
My ULA prefix is fd00::/64, so I chose fd00:0001::/64 for the wireguard's. For me, this seems to be equivalent to the ipv4 config with 192.168.178.0/24 and 172.27.66.1/24.

**Comment by TimoFriedri** [comment]
More info here
https://community.home-assistant.io/t/no-ipv6-on-ha-addons-wireguard-ipv6-only-provider/284691/3
