### ISSUE TITLE
[enhancement] Add IPv6 support

### ISSUE THREAD

**Issue by TimoFriedri** [hassio-addons/addon-wireguard#84]
# Problem/Motivation

I am now quite sure that with the current state, IPv6 does not work.
Related issue: #82 

## Expected behavior

Connection succeeds as with IPv4.

## Actual behavior

Client manages to contact to the WG server, but Server can't send back data to the client --> no handshake

## Steps to reproduce

Have a Wireguard client with an IPv6 only endpoint address. Click connect. Use Wireguard Home Assistant plugin as server.

## Proposed changes

I can see in the terminal of the Wireguard container:

```
root@a0d7b954-wireguard:/$ ping google.de -6
PING google.de (2a00:1450:400e:80e::2003): 56 data bytes
ping: sendto: Address not available
root@a0d7b954-wireguard:/$ 
```
Obviously, WG can't send IPv6 traffic, because there is no IPv6.

See:
```
root@a0d7b954-wireguard:/$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 172.27.66.1/24 scope global wg0
       valid_lft forever preferred_lft forever
36: eth0@if37: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:1e:21:07 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.30.33.7/23 brd 172.30.33.255 scope global eth0
       valid_lft forever preferred_lft forever
root@a0d7b954-wireguard:/$
```
This is my docker setup as created by the supervised install script:
![image](https://user-images.githubusercontent.com/19408741/109473368-7e140100-7a73-11eb-8e72-8545157e18f4.png)

I think the whole setup needs IPv6 addresses?!

For me IPv6 is very important, because I now only have a unique IPv6 with my new provider.
Thanks

**Comment by frenck** [comment]
> I think the whole setup needs IPv6 addresses?!

Should not be needed, as it is exposed by port on Docker on the host (which has the IPv6 address).

```
root@a0d7b954-wireguard:/$ ping google.de -6
PING google.de (2a00:1450:400e:80e::2003): 56 data bytes
ping: sendto: Address not available
```

That makes sense, as the containers/addons themselves have no IPv6. This is not something the add-on can fix.

**Comment by TimoFriedri** [comment]
Ok, but fact is, it does not work. So where to initiate an Issue to solve this ?
