### ISSUE TITLE
Are we sure that 172.30.32.1 is still the AdGuard DNS address?

### ISSUE THREAD

**Issue by ndarilek** [hassio-addons/addon-wireguard#91]
# Problem/Motivation

WireGuard used to work OK for me, but hasn't for the past month or so. Essentially, I can ping out of my network, but DNS resolution takes a long time or fails completely. No configuration changes, other than upgrading HA core/supervisor/OS/the addon, were made over that time. I suspect the instances of DNS resolution that take a while are due to platforms using fallback methods that ultimately resolve, and when I take steps to remove those, DNS resolution reliably fails.

## Expected behavior

Wireguard works like it used to on Android, iOS and Windows.

## Actual behavior

Wireguard connects and pings out, but DNS fails to resolve. I have 0.0.0.0/0 as allowed IPs on my client, and 172.30.32.1 as the DNS address.

## Steps to reproduce

1. Install this addon.
2. Install the AdGuard addon.
3. Use this configuration:

```yaml
server:
  host: <something>
  addresses:
    - 172.27.66.1
  dns:
    - 172.30.32.1
peers:
  - name: windowsdesktop
    addresses:
      - 172.27.66.2
    allowed_ips: []
    client_allowed_ips: []
```

4. Load the generated configuration into a client. In my case I used the Windows desktop client.
5. Edit the tunnel to kill traffic that doesn't use Wireguard.
6. Ping 172.30.32.1, noting that it is pingable.
7. nslookup yahoo.com 172.30.32.1. For me it times out.
8. ping 8.8.8.8. Note that it works.
9. Kill the Wireguard tunnel, and run a nslookup against the IP of the HA instance. Note that, over the external IP, AdGuard seems to resolve quickly.

It seems odd that these IPs would change and I'd be the only one to notice, but I haven't touched this config since setting it up. I've also tried everything I can think to do, including setting my external hostname to resolve to my local IP so the connection only traverses the local network when I'm at home. Also, my HA app connects directly to my instance, so that much seems to work. I can't think of another reason for this to fail across all of my devices--Windows desktop, Android, and iOS--when it worked fine for months, and when I've done nothing other than updating components.

Thanks.

**Comment by frenck** [comment]
See AdGuard add-on. Not related to WireGuard.

**Comment by ndarilek** [comment]
It seems related in that your docs explicitly specify that IP. I'd think 
you'd want it open if only to track that your docs may no longer be 
accurate.

**Comment by frenck** [comment]
There is a PR open for that.
